spring:
  application:
    name: resumebuilderapi
  profiles:
    active: dev
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: resumebuilder
  # Mail Info
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
        from: ${MAIL_FROM}
    protocol: smtp

# App base
app:
  base:
    url: http://localhost:8080/
  mail:
    from: ${MAIL_FROM}

# Cloudinary Info
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}